# https://github.com/elastic/elasticsearch-docker.
FROM docker.elastic.co/elasticsearch/elasticsearch:7.1.1

# COPY ./plugins/opendistro_alerting-1.0.0.0.zip /plugins/

# RUN bin/elasticsearch-plugin install file:///plugins/opendistro_alerting-1.0.0.0.zip
